Logs
MikhailKolesnikov321/kolesnikov_newsfeed pull request #12
Opened 2023-11-14 07:22 UTC by MikhailKolesnikov321

2023-11-14 07:36 UTC, MVlasovD requested changes

2023-11-14 07:36 UTC, MVlasovD commented on src/main/java/com/example/kolesnikov_advancedServer/entities/LogEntity.java
> +    @Column(nullable = false)
поля могут быть какие угодно, такие которые тебе нужно записать в БД

2023-11-14 07:36 UTC, MVlasovD commented on src/main/java/com/example/kolesnikov_advancedServer/entities/NewsEntity.java
> +    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
почему поменял тип каскада

2023-11-14 08:12 UTC, MikhailKolesnikov321 commented on src/main/java/com/example/kolesnikov_advancedServer/entities/NewsEntity.java
> +    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
при удалении новости, удалялся пользователь, который создал новость)

2023-11-15 12:53 UTC, MVlasovD approved these changes

2023-11-15 12:53 UTC, merged