User data change
MikhailKolesnikov321/kolesnikov_newsfeed pull request #5
Opened 2023-11-03 09:33 UTC by MikhailKolesnikov321

2023-11-03 13:42 UTC, MVlasovD requested changes

2023-11-03 13:42 UTC, MVlasovD commented on src/main/java/com/example/kolesnikov_advancedServer/entities/UserEntity.java
>      private String token;
зачем?

2023-11-08 06:49 UTC, MikhailKolesnikov321 commented on src/main/java/com/example/kolesnikov_advancedServer/entities/UserEntity.java
>      private String token;
для того, чтобы поле не появлялось в бд

2023-11-08 08:40 UTC, MVlasovD approved these changes

2023-11-08 08:40 UTC, merged